Version detector

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -86,14 +86,52 @@ jobs:
             console.log(`Release type: ${releaseType}`)
             return releaseType
 
+      - name: Set version from tag to environment variable
+        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+
+      - name: Get version strategy
+        if: startsWith(github.ref, 'refs/tags/') && matrix.publish
+        run: |
+          CURRENT_VERSION=$(jq -r '.version' packages/create-common/package.json)
+          NEW_VERSION=${{ env.RELEASE_VERSION }}
+
+          if [[ -z "$NEW_VERSION" ]]; then
+            echo "Error: You must provide the new version as an argument."
+            exit 1
+          fi
+
+          IFS='.' read -r CUR_MAJOR CUR_MINOR CUR_PATCH <<< "$(echo $CURRENT_VERSION | cut -d'-' -f1)"
+          CUR_PRERELEASE=$(echo "$CURRENT_VERSION" | grep -oP '(?<=-).*')
+
+          IFS='.' read -r NEW_MAJOR NEW_MINOR NEW_PATCH <<< "$(echo $NEW_VERSION | cut -d'-' -f1)"
+          NEW_PRERELEASE=$(echo "$NEW_VERSION" | grep -oP '(?<=-).*')
+
+          VERSION_STRATEGY=""
+          # Detect the type of version change
+          if [[ "$NEW_MAJOR" -gt "$CUR_MAJOR" ]]; then
+            VERSION_STRATEGY="major"
+            echo "Strategy: Major version update (X.0.0)"
+          elif [[ "$NEW_MINOR" -gt "$CUR_MINOR" ]]; then
+            VERSION_STRATEGY="minor"
+            echo "Strategy: Minor version update (0.X.0)"
+          elif [[ "$NEW_PATCH" -gt "$CUR_PATCH" ]]; then
+            VERSION_STRATEGY="patch"
+            echo "Strategy: Patch version update (0.0.X)"
+          elif [[ -n "$NEW_PRERELEASE" ]] && [[ "$NEW_PRERELEASE" != "$CUR_PRERELEASE" ]]; then
+            VERSION_STRATEGY="prerelease"
+            echo "Strategy: Pre-release update (0.0.0-X)"
+          else
+            echo "Error: No version increase detected"
+            exit 1
+          fi
+
+          echo "VERSION_STRATEGY=${VERSION_STRATEGY}" >> $GITHUB_ENV
+
       # TODO: Enable after reaching 1.0.0.
       # This may indicate that the tag set has a typo, e.g., alpah, betta, etc.
       # - name: Verify tag format
       #   if: steps.check-tag-format.outputs.is_stable == 'false' && steps.get-release-type.outputs.result == 'latest'
       #   run: echo "Tag set may be incorrect. Please, review" && exit 1
-
-      - name: Set version from tag to environment variable
-        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
 
       - name: Configure yarn to publish packages
         if: startsWith(github.ref, 'refs/tags/') && matrix.publish
@@ -111,8 +149,12 @@ jobs:
           RELEASE_TYPE: ${{ steps.get-release-type.outputs.result }}
         run: |
           set -x
-          yarn version --new-version ${{ env.RELEASE_VERSION }}
-          yarn postversion
+          for d in $(ls packages); 
+          do
+            echo "Package: $d"
+            yarn version ${{ env.VERSION_STRATEGY }}
+            yarn postversion
+          done
 
       # - name: Ignore changes to .yarnrc.yml
       #   if: startsWith(github.ref, 'refs/tags/') && matrix.publish
